CREATE DATABASE ManagementCustomer;
GO

USE [ManagementCustomer]
GO

CREATE TABLE Customer (
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Address VARCHAR(50) NOT NULL,
	Email VARCHAR(100) NOT NULL
)
GO

CREATE TABLE [User] (
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	[Login] VARCHAR(50) NOT NULL,
	[Password] VARCHAR(100) NOT NULL,
	[Role] VARCHAR(20) NOT NULL
)
