version: "3.9"
services:
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    container_name: 'sqlserver'
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Test2023"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
    
  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    command: >
      bash -c '
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P ${Sa_Password:-Test2023} -d master -i docker-entrypoint-initdb.d/init.sql;
      echo "All done!";
      '  