version: "3.9"
services:
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    container_name: 'sqlserver'
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Test2023"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log